config/routes.rb
AachenGestalten::Application.routes.draw do
  resources :initiatives, path: 'initiativen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments

    member do
      get 'contact'
      post 'contact', action: 'contact_submit'

      get 'contact_moderator'
      post 'contact_moderator', action: 'contact_moderator_submit'

      post 'subscribe'
      post 'unsubscribe'

      post 'support'
      post 'unsupport'
    end
  end

  resources :kommunens, path: 'kommunen'

  resources :constructions, path: 'baustellen'

  resources :quarters, path: 'quartier' do
    member do
      get :initiatives
      get :streets

      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :kommunens, path: 'kommunen' do
    member do
      get :quartiere
    end
  end

  resources :antraeges, controller: 'antraege', path: 'vorlagen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments
  end

  resources :pages, path: 'seite', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :neuigkeitens, controller: 'neuigkeiten', path: 'veranstaltungen', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :banners, :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :search_subscriptions do
    member do
      get 'confirm'
    end
  end

  resources :categories, :path_names => {:new => "neu", :edit => "bearbeiten"}

  get 'search' => 'search#index'
  get 'markers' => 'markers#index'

  resources :profiles, :path_names => {:new => "neu", :edit => "bearbeiten"} do
    member do
      post :assign_moderator
      post :remove_moderator

      post :block
      post :unblock

      get 'note', action: 'edit_note'
      put 'note', action: 'update_note'
    end
  end

  resources :widgets, :path_names => {:new => "neu", :edit => "bearbeiten"}

  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  get 'nutzerverwaltung' => "profiles#manage_users", :as => 'manage_users'

  match 'dashboard' => 'pages#dashboard'
  match 'start' => 'pages#start'

  root :to => "pages#start"

  get '/:slug' => 'pages#show', as: 'static'

end

app/models/quarter.rb
class Quarter
  include Cacheable

  attr_reader :id, :name, :lat, :long, :kommune

  def initialize(id, name, lat=nil, long=nil, kommune=nil)
    @id = id
    @name = name
    @lat = lat
    @long = long
    @kommune = kommune
  end

  def self.find(id)
    result = CartoDB::Connection.row("aachen_quartiere", id)
    row = result
    new(row[:cartodb_id], row[:name], row[:latitude], row[:longitude], row[:kommune])
  end

  def self.all
    cache do
      fetch_quarters
    end
  end

  def self.fetch_quarters
    result = CartoDB::Connection.query("SELECT cartodb_id, latitude, longitude, name, kommune FROM aachen_quartiere ORDER BY name ASC")
    result[:rows].map do |row|
      Quarter.new(row[:cartodb_id], row[:name], row[:latitude], row[:longitude], row[:kommune])
    end
  end

  def self.fetch_quarters_with_ids(ids)
    result = CartoDB::Connection.query("SELECT cartodb_id, latitude, longitude, name, kommune FROM aachen_quartiere WHERE cartodb_id IN (#{ids.join(',')}) ORDER BY name ASC")
    result[:rows].map do |row|
      Quarter.new(row[:cartodb_id], row[:name], row[:latitude], row[:longitude], row[:kommune])
    end
  end

  def self.id_for_coordinates(lat, long)
    result = CartoDB::Connection.query("SELECT cartodb_id FROM aachen_quartiere where ST_contains(the_geom, st_pointfromText('POINT(#{lat} #{long})', 4326)) LIMIT 1")
    (result[:rows].first || {})[:cartodb_id]
  end

  def coordinates
    "#{lat}, #{long}"
  end

  def streets
    result = CartoDB::Connection.query("SELECT strasse AS street, ST_X(ST_PointOnSurface(the_geom)) AS long, ST_Y(ST_PointOnSurface(the_geom)) AS lat, cartodb_id from aachen_streets_quartiere where name = '#{@name}' order by strasse")
    result[:rows].map do |row|
      Street.new(row[:cartodb_id], row[:street], row[:lat], row[:long])
    end
  end
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  def show
    @quarter_id = params[:id]
    @quarter = Quarter.find(params[:id])
    @initiatives = Initiative.with_location.within_quarter(params[:id]).where('visible = true')
    @streets = @quarter.streets
    @quarters = Quarter.all
    @antraeges = Antraege.with_location.within_quarter(params[:id]).select([:id, :kommune, :title, :lat, :long]).order('last_updated desc').limit(100)
    @comments = Comment.for_items(@initiatives.pluck(:id), @antraeges.pluck(:id)).recent
    @constructions = Construction.within_quarter(params[:id]).current.with_location.order('start_date DESC').limit(100)
    @selected_quarter = params[:id]
    @selected_kommune = @quarter.kommune
  end

  def initiatives
    initiatives = Initiative.within_quarter(params[:id])
    render json: initiatives
  end

  def streets
    # TODO: Sanitize the params[:name] for malicious SQL - checkx
    render json: Quarter.new(nil, params[:id]).streets
  end

  def subscribe
    @quarter_id = params[:id]
    unless current_user.quarter_subscriptions.exists?(quarter_id: params[:id])
      current_user.quarter_subscriptions.create!(quarter_id: params[:id])
    end

    @subscribed = true

    respond_to do |format|
      format.js { render 'update_subscription' }
    end
  end

  def unsubscribe
    @quarter_id = params[:id]
    if subscription = current_user.quarter_subscriptions.where(quarter_id: params[:id]).first
      subscription.destroy
    end

    @subscribed = false

    respond_to do |format|
      format.js { render 'update_subscription' }
    end
  end
end

app/views/quarters/_subscribe_button.html.haml
%div{'data-subscribe-id' => @quarter_id}
  - if @subscribed
    = button_to "E-Mail Abo beenden", unsubscribe_quarter_path(@quarter_id), :method => :post, :remote => true, :class => 'button radius', :style => "width: 100%"
  - else
    = button_to "E-Mail Abo", subscribe_quarter_path(@quarter_id), :method => :post, :remote => true, :class => 'button radius', :style => "width: 100%"

app/views/quarters/show.html.haml
- title @quarter.name

.large-8.medium-8.columns
  .shape.filter
    .row
      .large-4.columns
        %b
          %span#kommune{style: "font-weight: bold; margin-right: 10px;"}
            = @quarter.kommune
          = @quarter.name
      .large-6.columns
        .filter-quartiere{:style => "margin-top: -4px;"}
          = select_tag 'streets', options_from_collection_for_select(@streets, 'coordinates', 'name'), class: 'chosen', include_blank: true, data: { optional: true, placeholder: 'Strasse auswählen'}
      .large-2.columns

  .box-center
    #map.quarter-page{:style => "width: auto; height: 501px; border: 1px solid #ccc;", :data => { coords: [@quarter.lat, @quarter.long], initiatives: @initiatives.to_json, antraeges: @antraeges.to_json, constructions: @constructions.to_json }}
    #spinner

  #seitenverweis

.large-4.medium-4.columns
  = render 'widgets/recent_initiatives'
  = render 'widgets/start_initiative'
  %p
    = render 'subscribe_button' if current_user


= render 'initiatives/markers', initiatives: @initiatives

app/views/quarters/update_subscription.js.erb
$('div[data-subscribe-id="<%= @quarter_id %>"]').replaceWith("<%= escape_javascript(render('subscribe_button')) %>");