config/routes.rb
AachenGestalten::Application.routes.draw do
  resources :initiatives, path: 'initiativen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments

    member do
      get 'contact'
      post 'contact', action: 'contact_submit'

      get 'contact_moderator'
      post 'contact_moderator', action: 'contact_moderator_submit'

      post 'subscribe'
      post 'unsubscribe'

      post 'support'
      post 'unsupport'
    end
  end

  resources :kommunens, path: 'kommunen'

  resources :constructions, path: 'baustellen'

  resources :quarters, path: 'quartier' do
    member do
      get :initiatives
      get :streets

      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :kommunens, path: 'kommunen' do
    member do
      get :quartiere
    end
  end

  resources :antraeges, controller: 'antraege', path: 'vorlagen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments
  end

  resources :pages, path: 'seite', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :neuigkeitens, controller: 'neuigkeiten', path: 'veranstaltungen', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :banners, :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :search_subscriptions do
    member do
      get 'confirm'
    end
  end

  resources :categories, :path_names => {:new => "neu", :edit => "bearbeiten"}

  get 'search' => 'search#index'
  get 'markers' => 'markers#index'

  resources :profiles, :path_names => {:new => "neu", :edit => "bearbeiten"} do
    member do
      post :assign_moderator
      post :remove_moderator

      post :block
      post :unblock

      get 'note', action: 'edit_note'
      put 'note', action: 'update_note'
    end
  end

  resources :widgets, :path_names => {:new => "neu", :edit => "bearbeiten"}

  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  get 'nutzerverwaltung' => "profiles#manage_users", :as => 'manage_users'

  match 'dashboard' => 'pages#dashboard'
  match 'start' => 'pages#start'

  root :to => "pages#start"

  get '/:slug' => 'pages#show', as: 'static'

end

app/models/antraege.rb
class Antraege < ActiveRecord::Base
  include Geodata

  attr_accessible :begruendung, :betreff, :datum, :ergebnisse, :title, :verfasser, :link, :federfuehrend, :kommune, :content, :lat, :long, :last_updated, :check

  has_many :comments, as: :commentable
  has_and_belongs_to_many :categories, join_table: 'categories_antraeges'

  has_many :consultations, class_name: 'AntraegeConsultation'

  scope :search, ->(text) do
    where('title ILIKE ? or content ILIKE ?', "%#{text}%", "%#{text}%")
  end

  scope :recent, limit(3).order("last_updated desc")
  scope :with_location, ->{ where("lat != ''") }
  scope :created_after, ->(timestamp) { where('created_at > ?', timestamp) }
  scope :updated_after, ->(timestamp) { where('created_at <= ?', timestamp).where('updated_at > ?', timestamp) }

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  include Geodata

  attr_accessible :content, :erreicht, :getan, :lat, :long, :title, :remove_file, :file, :fotos_attributes, :user_id, :category_ids, :visible, :kommune_feld, :last_reminder

  belongs_to :user
  has_many :fotos, :as => :attachable
  has_many :neuigkeitens
  has_many :subscriptions, :as => :subscribable, dependent: :destroy
  has_many :supporters, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_and_belongs_to_many :categories, join_table: 'categories_initiatives'
  accepts_nested_attributes_for :fotos, :allow_destroy => true, :reject_if => lambda { |a| a[:title].blank? && a[:file].blank? }

  validates_presence_of :categories, :content, :user_id, :title, :message => :is_required

  before_save :update_quarter_id

  scope :recent, limit(6).order("created_at desc").where('visible = true')
  scope :active, limit(5).order("updated_at desc").where('visible = true')
  scope :with_location, ->{ where("lat != ''") }
  scope :created_after, ->(timestamp) { where('created_at > ?', timestamp) }
  scope :updated_after, ->(timestamp) { where('created_at <= ?', timestamp).where('updated_at > ?', timestamp) }

  scope :search, ->(text) do
    where('title ILIKE ? or content ILIKE ?', "%#{text}%", "%#{text}%")
  end

  def subscribe(user)
    unless subscriptions.exists?(user_id: user.id)
      subscriptions.create!(user: user)
    end
  end

  def unsubscribe(user)
    if subscription = subscriptions.find_by_user_id(user.id)
      subscription.destroy
    end
  end

  def update_quarter_id
    if (lat_changed? || long_changed?) && lat.present? && long.present?
      self.quarter_id = Quarter.id_for_coordinates(long, lat)
    end
  end

end

app/controllers/initiatives_controller.rb
# encoding: utf-8

class InitiativesController < ApplicationController
  load_and_authorize_resource except: [:index]
  include LocationVariables

  def index
    @initiatives, @initiatives_map = search_models Initiative, params

    authorize! :index, Initiative

    respond_to do |format|
      format.html
      format.json do
        render json: json_for(@initiatives, @map_lat, @map_lng, @map_zoom)
      end
    end
  end

  def show
    @comments = @initiative.comments.arrange(:order => :created_at)

    if current_user
      @supporting = current_user.sympathies.exists?(:initiative_id => @initiative.id)
      @subscribed = current_user.subscriptions.exists?(:subscribable_id => @initiative.id, :subscribable_type => 'Initiative')
    end

    respond_to do |format|
      format.html
      format.json { render json: @initiative }
    end
  end

  def new
    @initiative = Initiative.new
    load_kommunen
    load_quarters

    respond_to do |format|
      format.html
      format.json { render json: @initiative }
    end
  end

  def edit
    load_kommunen
    load_quarters
  end

  def create
    @initiative = current_user.initiatives.build(params[:initiative])
    @initiative.visible = params[:visible].present? ? params[:visible] : true
    @initiative.subscriptions.build(user: current_user)

    respond_to do |format|
      if @initiative.save
        notificaiton = {
          Initiative => { new: [@initiative] }
        }
        QuarterSubscription.where('user_id != ?', current_user.id).where(quarter_id: @initiative.quarter_id).each do |subscription|
          SubscriptionMailer.quarter(subscription, notificaiton).deliver
        end

        format.html { redirect_to @initiative, notice: 'Die Initiative wurde erfolgreich erstellt.' }
        format.json { render json: @initiative, status: :created, location: @initiative }
      else
        format.html do
          load_quarters
          load_kommunen
          render action: "new"
        end
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @initiative.update_attributes(params[:initiative])
        notificaiton = {
          Initiative => { updated: [@initiative] }
        }
        # if @initiative.visible == true
        # QuarterSubscription.where('user_id != ?', current_user.id).where(quarter_id: @initiative.quarter_id).each do |subscription|
        #   SubscriptionMailer.notify(subscription, notificaiton).deliver
        # end
        # end
        # Send to subscriber
        format.html { redirect_to @initiative, notice: 'Die Initiative wurde erfolgreich gepeichert.' }
        format.json { head :no_content }
      else
        format.html do
          load_quarters
          load_kommunen
          render action: "edit"
        end
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @initiative.destroy

    respond_to do |format|
      format.html { redirect_to initiatives_url, notice: 'Initiative erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  def support
    @initiative = Initiative.find(params[:id])
    unless @initiative.supporters.exists?(user_id: current_user.id)
      @initiative.supporters.create!(user: current_user)
    end

    @initiative.subscribe(current_user)

    @supporting = true

    respond_to do |format|
      format.js { render 'update_support' }
    end
  end

  def unsupport
    @initiative = Initiative.find(params[:id])
    if supporter = @initiative.supporters.find_by_user_id(current_user.id)
      supporter.destroy
    end

    @supporting = false

    respond_to do |format|
      format.js { render 'update_support' }
    end
  end

  def subscribe
    @initiative = Initiative.find(params[:id])
    @initiative.subscribe(current_user)

    @subscribed = true

    respond_to do |format|
      format.js { render 'update_subscription' }
    end
  end

  def unsubscribe
    @initiative = Initiative.find(params[:id])
    @initiative.unsubscribe(current_user)

    @subscribed = false

    respond_to do |format|
      format.js { render 'update_subscription' }
    end
  end

  def contact
    @initiative = Initiative.find(params[:id])
    render 'kontakt_form'
  end

  def contact_submit
    @initiative = Initiative.find(params[:id])
    text = params[:message][:body]
    respond_to do |format|
      if text.present?
        InitiativenMailer.initiator_email(current_user, @initiative, text).deliver
        format.html { redirect_to @initiative, notice: 'Die Nachricht wurde verschickt.' }
      else
        flash.now[:alert] = 'Leider keine Nachricht vorhanden.'
        format.html { redirect_to contact_initiative_path, notice: 'Ein Text für eine Nachricht fehlt.' }
      end
    end
  end

  def contact_moderator
    @initiative = Initiative.find(params[:id])
    render 'kontakt_moderator'
  end

  def contact_moderator_submit
    @initiative = Initiative.find(params[:id])
    text = params[:message][:body]
    respond_to do |format|
      if text.present?
        InitiativenMailer.initiator_moderator_email(current_user, @initiative, text).deliver

        format.html { redirect_to @initiative, notice: 'Die Nachricht wurde verschickt.' }
      else
        flash.now[:alert] = 'Leider keine Nachricht vorhanden.'
        format.html { redirect_to contact_moderator_initiative_path, notice: 'Ein Text für eine Nachricht fehlt.' }
      end
    end
  end

  private

  delegate :link_to, :escape_javascript, :truncate_html, :to => :view_context

  def json_for(initiatives, lat, lon, zoom)
    {
      :initiatives => initiatives.as_json.map do |initiative|
        initiative.merge({
          :popup => "<b>#{link_to initiative['title'], initiative_path(initiative)}</b>" +
          "<br><p>#{escape_javascript(truncate_html(initiative['content'].html_safe, :length => 50))}</p>" +
          "#{link_to 'Zur Initiative', initiative_path(initiative)}"
        })
      end,

      # To center map
      :location => {:lat => lat, :lon => lon},
      :zoom => zoom
    }
  end

  def load_kommunen
    @kommunen = Kommune.all
  end

  def load_quarters
    @quarters = []
    quarters = Quarter.all.sort_by(&:name)
    @quarters_id_to_location = quarters.each_with_object({}) do |quarter, hash|
      hash[quarter.id] = [quarter.lat, quarter.long]
    end
  end
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
  def add_active_class(controller_name, action_name=nil, param_name=nil, param_value=nil)
    classes = ''
    if (params[:controller] == controller_name) && (action_name.nil? || (params[:action] == action_name)) &&
      (param_name.nil? || (params[param_name] == param_value))
      classes << " active"
    end
    return classes
  end

  def recent_initiatives
    @recent_initiatives ||= (@initiatives.try(:recent) || Initiative.recent)
  end
end

app/views/initiatives/_form.html.haml
= nested_form_for(@initiative, :html => { :id => "", :class => '', :multipart => true }) do |f|
  - if @initiative.errors.any?
    #error_explanation
      %h2= "Die Initiative konnte nicht gespeichert werden:"
      - @initiative.errors.full_messages.each do |msg|
        .alert-box.round
          = msg

  %fieldset.shape
    .row
      .large-8.columns
        %h3
          = f.label "Titel"
        = f.text_field :title
        - if current_user.admin? or current_user.moderator? or current_user.superadmin?
          .shape.grey
            %label{:for => "checkbox"}
              = f.check_box :visible, {:default => true, :checked => ("checked" if @initiative.visible == true)}
              %span{:class => "custom checkbox"}
              %b Initiative ist für normale Nutzer sichtbar
        %h3
          = f.label "Beschreibung"
        = f.text_area :content, :class => "smaller-textarea", :id => "redactor_content"
        %h3{:style => "margin-top: 15px;"}
          %label
            Fototitel
        = f.fields_for :fotos do |image_form|
          .image-upload
            = image_form.text_field :title, :class => ''
            - if image_form.object.new_record?
              = image_form.label "Bild", :class => ''
              = image_form.label :file, :class => "button" do
                = image_form.file_field :file, :class => ''
              %span.file-name
                = image_form.link_to_remove "Bild löschen"
            - if not image_form.object.new_record?
              = image_tag(image_form.object.file_url(:thumb).to_s, width: 125, height: 125, :class => 'form-photo')
              %label{:for => "checkbox"}
              = image_form.check_box :_destroy, :id => "checkbox"
              %label
                %b Bild Löschen
        = f.link_to_add "Bild hinzufügen", :fotos, :class => "button radius secondary"
        %h3
          = f.label "Was willst Du erreichen?"
        = f.text_area :erreicht, :class => "smaller-textarea"
        %h3
          = f.label "Was hast Du bisher getan?"
        = f.text_area :getan, :class => "smaller-textarea"
      .large-4.columns
        %h3
          = f.label "Kategorien   "
        = f.select :category_ids, Category.all.map { |c| [c.name, c.id] }, {include_blank: 'Keine ausgewählt'}
        %h3
          = f.label "Orte"
          = f.text_field :kommune_feld
    .row.spacetop
      .large-8.columns.spacetop
        #map{:style => "width: auto; height: 350px; border: 1px solid #ccc;"}
        = f.hidden_field "lat"
        = f.hidden_field "long"
      .large-4.columns.spacetop
        = select_tag 'initiative_kommune', options_from_collection_for_select(@kommunen, 'id', 'name'), class: 'model_kommune chosen', include_blank: true, data: { optional: true, placeholder: 'Ort auswählen' }
        = content_tag 'div', '', data: { quarters: @quarters_id_to_location }, style: 'display:none'
        = select_tag 'initiative_quarter', options_from_collection_for_select(@quarters, 'id', 'name'), include_blank: true, class: 'model_quarter chosen', data: { placeholder: 'Ortsteil'}
        = select_tag 'initiative_street', '', class: 'model_street chosen', include_blank: true, data: { placeholder: 'Strasse'}
        %p{:style => "margin-top: 20px"}
          %a{:href => 'javascript:void(0)', :class => 'button radius secondary remove-location'} Marker löschen

    .submit
      = f.submit "Speichern", :class => 'button radius'
      %span.cancel
        oder
      = link_to "Abbrechen", :back, :class => 'cancel'

= content_for :footer do
  :javascript
    $(document).ready(function() {
        $('#redactor_content').redactor({ lang: 'de', buttons: ['bold','italic','underline','|','unorderedlist','orderedlist','outdent','indent','|','link']});

    L.drawLocal.draw.handlers.marker.tooltip.start = 'Marker auf der Karte mit einem Klick positionieren';
    L.drawLocal.draw.toolbar.buttons.marker = 'Setze ein Punkt auf die Karte.';
    L.Icon.Default.imagePath = '/assets';

    var map;
    if( $('#initiative_long').val().length > 0 ) {
    map = new L.Map('map').setView(new L.LatLng($('#initiative_lat').val(), $('#initiative_long').val()), 13);
    }
    else {
    map = new L.Map('map').setView(new L.LatLng(50.775346 , 6.083887), 13);
    }
    var mapboxUrl = 'http://{s}.tiles.mapbox.com/v3/okf.map-najwtvl1/{z}/{x}/{y}.png',
        mapbox = new L.TileLayer(mapboxUrl, {"attribution": "\u00a9 <a href=\"http://www.openstreetmap.org/\" target=\"_blank\">OpenStreetMap</a> contributors"});
    map.addLayer(mapbox,true);
    map.scrollWheelZoom.disable();

    var drawControl = new L.Control.Draw({
        draw: {
            polygon: false,
            circle: false,
            polyline: false,
            rectangle: false
        }
    });

    map.addControl(drawControl);

    var drawnItems = new L.FeatureGroup();
    map.addLayer(drawnItems);

    if( $('#initiative_long').val().length > 0 ) {
      var marker = L.marker([$("#initiative_lat").val(), $("#initiative_long").val()]);
      drawnItems.addLayer(marker);
    }

    map.on('draw:created', function (e) {
      drawnItems.clearLayers();
      var marker = e.layer;
      marker.bindPopup('A popup!');
      drawnItems.addLayer(marker);
      $("#initiative_long").val(marker._latlng.lng)
      $("#initiative_lat").val(marker._latlng.lat)
    });
    map.addLayer(drawnItems);

      $('.remove-location').click(function () {
        drawnItems.clearLayers();
        $("#initiative_long").val('');
        $("#initiative_lat").val('');
      });

      $('#initiative_street').change(function() {
        var coords = $(this).val().split(',');
        $("#initiative_long").val(coords[1]);
        $("#initiative_lat").val(coords[0]);

        if( $('#initiative_long').val().length > 0 ) {
          drawnItems.clearLayers();
          var marker = L.marker(coords);
          drawnItems.addLayer(marker);
        }
      });

      var idToLocation = $('*[data-quarters]').data('quarters');
      $('#initiative_quarter').change(function () {
        var location = idToLocation[$(this).val()];
        map.setView(new L.LatLng(location[1], location[0]), 13);
      });
    });

app/views/initiatives/_subscribe_button.html.haml
%div{'data-subscribe-id' => @initiative.id}
  - if @subscribed
    = button_to "E-Mail Abo beenden", unsubscribe_initiative_path(@initiative), :method => :post, :remote => true, :class => 'button radius'
  - else
    = button_to "E-Mail Abo", subscribe_initiative_path(@initiative), :method => :post, :remote => true, :class => 'button radius'

app/views/initiatives/_support_button.html.haml
#support_button
  - if current_user
    - if @supporting
      = button_to "Unterstützung beenden", unsupport_initiative_path(@initiative), :method => :post, :remote =>   true, :class => 'start', :style => "width: 100%"
    - else
      = button_to "Initiative unterstützen", support_initiative_path(@initiative), :method => :post, :remote => true, :class => 'start', :style => "width: 100%"
  - else
    = link_to "Initiative unterstützen", '#', "data-reveal-id" => "login-window", class: "start"

app/views/initiatives/index.html.haml
= title "Initiativen"
= published_class

.row
  .large-12.columns
    - if @initiatives.blank?
      %h3
        Keine Initiativen
    - else
      - @initiatives.each do |initiative|
        - if initiative.visible == true or can? :update, initiative
          .wrapper-content
            .first-part
              %span
                = initiative.comments.count
                = "Kommentar".pluralize(initiative.comments.count)
              %span
                = initiative.supporters.count
                Unterstützer
            .wrapper-main
              - if foto = initiative.fotos.first
                = link_to image_tag(foto.file_url(:thumb).to_s, width: 125, height: 125, :class => 'photo'), foto.file_url(:lightbox).to_s, :class => "colorbox", :target => "_blank"
              .box1
                %span.date
                  = l initiative.created_at, :format => :short
                  %span
                    - if initiative.user
                      - if current_user
                        = link_to initiative.user.username, profile_path(initiative.user)
                      - else
                        = link_to initiative.user.username, '#', "data-reveal-id" => "login-window"
                  %span
                    - if !initiative.kommune_feld.blank?
                      #{initiative.kommune_feld}
                %h3.heading-post
                  = link_to initiative.title, initiative_path(initiative)
                  - if initiative.visible != true
                    .label.round.alert
                      Nicht veröffentlicht
                %p
                  = truncate_html(initiative.content.html_safe, length: 60)
              .box2
                .social
                  %span.icon-facebook-squared
                  %span.icon-twitter-squared
                = link_to "ansehen", initiative_path(initiative)

= paginate @initiatives

= content_for :footer do
  %script{ :type => 'text/javascript' }
    function initialize() {
    map = new L.Map('map').setView(new L.LatLng(#{@map_lat}, #{@map_lng}), #{@map_zoom});
    var mapboxUrl = 'http://{s}.tiles.mapbox.com/v3/okf.map-najwtvl1/{z}/{x}/{y}.png',
    mapbox = new L.TileLayer(mapboxUrl, {"attribution": "\u00a9 <a href=\"http://www.openstreetmap.org/\" target=\"_blank\">OpenStreetMap</a> contributors"});
    L.Icon.Default.imagePath = '/assets';
    map.addLayer(mapbox,true);
    map.scrollWheelZoom.disable();
    var initiativeIcon = L.AwesomeMarkers.icon({icon: 'initiative', color: 'red'});
    markers = []
    - i = 0
    - @initiatives_map.each do |initiative|
      - i += 1
      - if initiative.lat.present?
        marker#{i} = L.marker([#{initiative.lat}, #{initiative.long}], { icon: initiativeIcon }).addTo(map);
        marker#{i}.bindPopup('<b>#{link_to initiative.title, initiative_path(initiative)}</b><br>#{escape_javascript(truncate_html(initiative.content.html_safe, :length => 50))}#{link_to 'Zur Initiative', initiative_path(initiative)}');
        markers.push(marker#{i});
    }
    $(document).ready(function() {
    initialize();
    });

app/views/initiatives/show.html.haml
= title @initiative.title
= published_class

.row.initiative.show
  .large-8.columns
    .shape
      %h1{:style => "color: #414144"}
        = @initiative.title
    %ul.small-block-grid-4
      - for foto in @initiative.fotos
        %li
          = link_to image_tag(foto.file_url(:thumb).to_s, width: 125, height: 125, :class => 'avatar'), foto.file_url(:lightbox).to_s, :class => "th radius colorbox"
    .shape
      .row
        .large-10.columns
          .creator-image
            - if @initiative.user.present?
              = link_to image_tag(avatar_url(@initiative.user, 50), alt: @initiative.user.username, width: "50", height: "50", class: "avatar"), profile_path(@initiative.user)
          .creator-text
            Eine Initiative von
            %br
            - if @initiative.user.present?
              - if current_user
                #{link_to @initiative.user.username, profile_path(@initiative.user)}
              - else
                = @initiative.user.username
              - if @initiative.user.kommune_name.present?
                (#{@initiative.user.kommune_name})
          - if @initiative.visible != true
            .right
              .label.round.alert
                Initiative nicht veröffentlicht
        .large-2.columns
          = render 'initiatives/social_media_buttons', url: @initiative

      .content-frame
        %h3
          Worum geht's?
        %p.content
          = sanitize(auto_link(@initiative.content.html_safe, :all, :target => "_blank"), tags: %w(p b i ul ol li u a blockquote))
        %h3
          Was willst Du erreichen?
        %p.content
          - if @initiative.erreicht.present? 
            = sanitize(auto_link(@initiative.erreicht.html_safe, :all, :target => "_blank"), tags: %w(p b i ul ol li u a blockquote))
          - else
            Nichts
        %h3
          Was hast Du bereits getan?
        %p.content
          - if @initiative.getan.present?
            = sanitize(auto_link(@initiative.getan.html_safe, :all, :target => "_blank"), tags: %w(p b i ul ol li u a blockquote))
          - else
            Nichts
        .row
          .large-6.columns
            - if current_user && current_user != @initiative.user
              = render 'subscribe_button'
            - if current_user && (current_user != @initiative.user)
              = link_to 'Initiator kontaktieren', contact_initiative_path(@initiative), :class => 'button radius'
            - if current_user == @initiative.user
              = link_to 'Moderator kontaktieren', contact_moderator_initiative_path(@initiative), :class => 'button radius'
          .large-6.columns
            - if can? :edit, @initiative
              - if can? :edit, @initiative
                = link_to "Bearbeiten", edit_initiative_path(@initiative), :class => 'button radius'
              - if can? :destroy, @initiative
                = link_to @initiative, :confirm => "Sind Sie sich sicher?", :method => :delete, :class => 'button radius delete' do
                  Löschen
    .shape
      = render :partial => "comments/form", :locals => {:commentable => @initiative}

    - if @comments.present?
      %h2
        #{pluralize(@initiative.comments.count(:id), "Kommentar")}

      = nested_messages @comments if @comments

  .large-4.columns
    - if @initiative.lat?
      #map{:style => "width: auto; height: 350px; border: 1px solid #ccc;"}

    .holder-list.second
      %h3.title.second
        Veranstaltungen
      - if @initiative.neuigkeitens.exists?
        %ul
          - @initiative.neuigkeitens.each do |neuigkeit|
            %li
              = link_to neuigkeiten_path(neuigkeit) do
                = l neuigkeit.datum, :format => :short if neuigkeit.datum
                = truncate(neuigkeit.title, :length => 100, :omission => '...')
      - else
        .pad
          %p
            Noch keine Veranstaltungen.

      - if can? :edit, @initiative
        .pad
          = link_to "Veranstaltung einfügen", new_neuigkeiten_path(initiative_id: @initiative.id), :class => "button secondary tiny radius"

    .holder-list.second.infos
      %h3.title.second{:style => "background-color: #9a2e2e"}
        Infos
      .pad
        .row
          .large-5.small-5.medium-5.columns
            %p
              Kategorie
          .large-7.small-7.medium-7.columns
            - @initiative.categories.each do |cat|
              = cat.name
        .row
          .large-5.small-5.medium-5.columns
            %p
              Ort
          .large-7.small-7.medium-7.columns
            = @initiative.kommune_feld
        .row
          .large-5.small-5.medium-5.columns
            Start
          .large-7.small-7.medium-7.columns
            = l @initiative.created_at, :format => :short
        .row
          .large-5.small-5.medium-5.columns
            aktualisiert
          .large-7.small-7.medium-7.columns
            = l @initiative.updated_at, :format => :short

    - if current_user != @initiative.user
      = render 'support_button'

    .supporters.second
      %h3.title.second{:style => "background-color: #414144"}
        Unterstützer
        (#{@initiative.supporters.count})
      - if @initiative.supporters.exists?
        %ul#supporter
          - @initiative.supporters.each do |supporter|
            %li{:class => "support-#{supporter.user.id}"}
              = link_to image_tag(avatar_url(supporter.user, 50), alt: supporter.user.username, width: "50", height: "50", :class => "avatar-support avatar"), profile_path(supporter.user)
              %span.supporter
                = link_to supporter.user.username, profile_path(supporter.user)
              - if supporter.user.kommune_name.present?
                (#{supporter.user.kommune_name})

      - else
        %ul#supporter

- if @initiative.lat?
  = content_for :footer do
    :javascript
      var map = new L.Map('map').setView(new L.LatLng(#{@initiative.lat}, #{@initiative.long}), 17);

      var mapboxUrl = 'http://{s}.tiles.mapbox.com/v3/okf.map-najwtvl1/{z}/{x}/{y}.png',
          mapbox = new L.TileLayer(mapboxUrl, {"attribution": "\u00a9 <a href=\"http://www.openstreetmap.org/\" target=\"_blank\">OpenStreetMap</a> contributors"});
      map.addLayer(mapbox,true);
      map.scrollWheelZoom.disable();

    %script{ :type => 'text/javascript' }
      - if @initiative.lat.present?
        var initiativeIcon = L.AwesomeMarkers.icon({icon: 'initiative', color: 'red'});
        marker = L.marker([#{@initiative.lat}, #{@initiative.long}], { icon: initiativeIcon }).addTo(map);

app/views/initiatives/update_support.js.erb
$('#support_button').html("<%= escape_javascript(render('support_button')) %>");
<% if @supporting == false %>
$('li.support-<%= current_user.id%>').slideUp(600);
<% else %>
$('ul#supporter').append('<li class="-<%= current_user.id%>"><%= link_to image_tag(avatar_url(current_user, 25), alt: current_user.username, class: "avatar-support avatar", width: "25", height: "25"), profile_path(current_user)%><%= link_to current_user.username, profile_path(current_user) %></li>').slideDown(1000);
<% end %>