config/routes.rb
AachenGestalten::Application.routes.draw do
  resources :initiatives, path: 'initiativen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments

    member do
      get 'contact'
      post 'contact', action: 'contact_submit'

      get 'contact_moderator'
      post 'contact_moderator', action: 'contact_moderator_submit'

      post 'subscribe'
      post 'unsubscribe'

      post 'support'
      post 'unsupport'
    end
  end

  resources :kommunens, path: 'kommunen'

  resources :constructions, path: 'baustellen'

  resources :quarters, path: 'quartier' do
    member do
      get :initiatives
      get :streets

      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :kommunens, path: 'kommunen' do
    member do
      get :quartiere
    end
  end

  resources :antraeges, controller: 'antraege', path: 'vorlagen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments
  end

  resources :pages, path: 'seite', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :neuigkeitens, controller: 'neuigkeiten', path: 'veranstaltungen', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :banners, :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :search_subscriptions do
    member do
      get 'confirm'
    end
  end

  resources :categories, :path_names => {:new => "neu", :edit => "bearbeiten"}

  get 'search' => 'search#index'
  get 'markers' => 'markers#index'

  resources :profiles, :path_names => {:new => "neu", :edit => "bearbeiten"} do
    member do
      post :assign_moderator
      post :remove_moderator

      post :block
      post :unblock

      get 'note', action: 'edit_note'
      put 'note', action: 'update_note'
    end
  end

  resources :widgets, :path_names => {:new => "neu", :edit => "bearbeiten"}

  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  get 'nutzerverwaltung' => "profiles#manage_users", :as => 'manage_users'

  match 'dashboard' => 'pages#dashboard'
  match 'start' => 'pages#start'

  root :to => "pages#start"

  get '/:slug' => 'pages#show', as: 'static'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if Rails.env.production?
      @results = ThinkingSphinx.search(params[:q])
    else
      @results = Antraege.search(params[:q])
    end
  end
end

app/views/search/index.html.haml
= title "Suchergebnis: " + params[:q] if params[:q]
%h1
  Suchergebnis

.row
  .large-12.columns
    = form_tag search_path, method: :get, :class => "" do
      .row
        .large-7.columns
          = text_field_tag 'q', params[:q]
        .large-5.columns.left
          = submit_tag 'Suchen', :class => "button radius medium", :style => ""

.row
  .large-8.columns
    - if @results.present?
      - @results.each do |result|
        .shape
          %h2{:style => "font-size: 22px;"}
            = link_to truncate(result.title, length: 220), result
          - if result.content?
            %p
              = sanitize(truncate_html(result.content.html_safe, length: 200), tags: %w(br p))
    - else
      %h4
        Leider kein Treffer.
  .large-4.columns
    = link_to 'Stichwort abonnieren', new_search_subscription_path(query: params[:q]), class: 'button radius'
    .shape
      %p
        %b
          Per E-Mail über neue Inhalte zu dem Thema informiert werden.


= paginate @results