config/routes.rb
AachenGestalten::Application.routes.draw do
  resources :initiatives, path: 'initiativen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments

    member do
      get 'contact'
      post 'contact', action: 'contact_submit'

      get 'contact_moderator'
      post 'contact_moderator', action: 'contact_moderator_submit'

      post 'subscribe'
      post 'unsubscribe'

      post 'support'
      post 'unsupport'
    end
  end

  resources :kommunens, path: 'kommunen'

  resources :constructions, path: 'baustellen'

  resources :quarters, path: 'quartier' do
    member do
      get :initiatives
      get :streets

      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :kommunens, path: 'kommunen' do
    member do
      get :quartiere
    end
  end

  resources :antraeges, controller: 'antraege', path: 'vorlagen', :path_names => {:new => "neu", :edit => "bearbeiten"} do
    resources :comments
  end

  resources :pages, path: 'seite', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :neuigkeitens, controller: 'neuigkeiten', path: 'veranstaltungen', :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :banners, :path_names => {:new => "neu", :edit => "bearbeiten"}

  resources :search_subscriptions do
    member do
      get 'confirm'
    end
  end

  resources :categories, :path_names => {:new => "neu", :edit => "bearbeiten"}

  get 'search' => 'search#index'
  get 'markers' => 'markers#index'

  resources :profiles, :path_names => {:new => "neu", :edit => "bearbeiten"} do
    member do
      post :assign_moderator
      post :remove_moderator

      post :block
      post :unblock

      get 'note', action: 'edit_note'
      put 'note', action: 'update_note'
    end
  end

  resources :widgets, :path_names => {:new => "neu", :edit => "bearbeiten"}

  devise_for :users, controllers: {
    registrations: 'user_registrations'
  }

  get 'nutzerverwaltung' => "profiles#manage_users", :as => 'manage_users'

  match 'dashboard' => 'pages#dashboard'
  match 'start' => 'pages#start'

  root :to => "pages#start"

  get '/:slug' => 'pages#show', as: 'static'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  self.inheritance_column = nil

  attr_accessible :type, :name, :content, :placements_attributes, :title

  has_many :placements, class_name: 'WidgetPlacement', dependent: :destroy
  accepts_nested_attributes_for :placements, :allow_destroy => true

  def partial_name
    {
      'recent_comments' => 'widgets/recent_comments',
      'static' => 'widgets/static',
      'recent_initiatives' => 'widgets/recent_initiatives',
      'recent_updated_initiatives' => 'widgets/recent_updated_initiatives',
      'recent_neuigkeiten' => 'widgets/recent_neuigkeiten',
      'start_iniative' => 'widgets/start_initiative',
      'recent_vorlagen' => "widgets/recent_vorlagen"
    }[type]
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  load_and_authorize_resource

  def index
    @widgets = Widget.order(:created_at).page params[:page]

    respond_to do |format|
      format.html
      format.json { render json: @widgets }
    end
  end

  def new
    @widget = Widget.new

    respond_to do |format|
      format.html
      format.json { render json: @widget }
    end
  end

  def edit
    @widget = Widget.find(params[:id])
  end

  def create
    @banner = Banner.new(params[:banner])

    respond_to do |format|
      if @widget.save
        format.html { redirect_to widgets_url, notice: 'Widget wurde erfolgreich gespeichert.' }
        format.json { render json: @widget, status: :created, location: @widget }
      else
        format.html { render action: "new" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to widgets_url, notice: 'Widget wurde erfolgreich gespeichert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  def any_widgets?(position)
    WidgetPlacement.for(params[:controller], params[:action], position).exists?
  end

  def render_widgets(position)
    placements = WidgetPlacement.for(params[:controller], params[:action], position)
    Widget.joins(:placements).merge(placements).inject(''.html_safe) do |output, widget|
      output << render_widget(widget)
    end
  end

  def render_widget(widget)
    render partial: widget.partial_name, locals: { widget: widget }
  end

  def get_recent_comments
    if @comments.nil?
      Comment.recent
    else
      @comments
    end
  end
end

app/views/widgets/_form.html.haml
= nested_form_for(@widget, :html => { :class => 'custom', :multipart => true }) do |f|
  - if @widget.errors.any?
    #error_explanation
      %ul
        - @widget.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    %h3
      = f.label "Typ", :class => ''
    = select(:widget, :type, [['Statischer Block', 'static'],['Letzte Kommentare', 'recent_comments'],['Letzte Veranstaltungen', 'recent_neuigkeiten'], ['Neue Initiativen','recent_initiatives'], ['Aktive Initiativen','recent_updated_initiatives'], ['Knopf Initiative starten', 'start_iniative'],['Neue Vorlagen', 'recent_vorlagen']])
    %h3
      = f.label "Name", :class => ''
    = f.text_field :name, :class => ''
    %h3
      = f.label "Titel", :class => ''
    = f.text_field :title, :class => ''
    %h3
      = f.label "Inhalt", :class => ''
    = f.text_area :content, :class => '', :id => 'redactor_content'
    %h2
      Sichtbarkeit
    = f.fields_for :placements do |d|
      .shape.grey
        %h3
          = d.label "Einzel- oder Index", :class => ''
        = d.select(:action, [['index', 'index'],['show', 'show'],['start', 'start']])
        %h3
          = d.label "Bereiche", :class => ''
        = d.select(:controller, [['Initiativen', 'initiatives'],['Normale Seiten', 'pages'],['Veranstaltungen', 'neuigkeiten'],['Ratsinfo', 'antraege'],['Ortsteil', 'quarters'],['Orte', 'kommunens'], ['Baustellen', 'constructions'], ['Profil', 'profiles']])
        %h3
          = d.label "Layout", :class => ''
        = d.select(:position, [['Rechte Spalte', 'sidebar'], ['Unter dem Inhalt','content_bottom'], ['Nirgends', 'nil']])
        %h3
          = d.label "Reihenfolge", :class => ''
        = d.select(:weight, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]])
        %label{:for => "checkbox"}
          = d.check_box :_destroy, :id => "checkbox"
          %label
            %b Löschen
    = f.link_to_add "Sichtbarkeit", :placements, :class => "button radius secondary"

    .submit
      = f.submit "Speichern", :class => 'button radius'
      %span.cancel
        oder
      = link_to "Abbrechen", widgets_url, :class => 'cancel'


= content_for :footer do
  :javascript
    $(document).ready(
      function()
      {
        $('#redactor_content').redactor({ lang: 'de', buttons: ['html','formatting','bold','italic','underline','|','unorderedlist', 'orderedlist','outdent','indent','|','link','table','image','fontcolor']});
      }
    );

app/views/widgets/_recent_comments.html.haml
#widget.shape.grey
  %h4
    %span.icon-bullseye.icon.turkis
    Neue Kommentare
  %ul.no-bullet
    - get_recent_comments.each do |comment|
      - next if (comment.commentable_type == 'Initiative') && (!comment.commentable.visible)
      %li
        - if comment.user
          -#= link_to image_tag(avatar_url(comment.user, 25), alt: comment.user.username, width: "25", height: "25"), profile_path(comment.user)
          - if current_user
            = link_to comment.user.username, profile_path(comment.user)
          - else
            = comment.user.username
          |
        - if comment.content
          = truncate(comment.content, :length => 50, :omission => '...').html_safe
        - if comment.commentable_type == 'Initiative'
          = link_to "mehr", initiative_path(comment.commentable.id)
        - if comment.commentable_type == 'Antraege'
          = link_to "mehr", antraege_path(comment.commentable.id)

app/views/widgets/_recent_constructions.html.haml
.holder-list.construction.fifth
  %h3.title.fifth Baustellen

  - if @constructions.present?
    %ul
      - @constructions.limit(3).each do |construction|
        %li
          = link_to construction_path(construction) do
            %span
              = construction.city
            %br/
            #{l construction.start_date, :format => :short} - #{l construction.end_date, :format => :short}
            %br
            = truncate(construction.title, :length => 50, :omission => '...')
  - else
    %ul
      %li
        Keine Baustellen
  = link_to "Alle Baustellen", constructions_path, :class => "alle"

app/views/widgets/_recent_initiatives.html.haml
.holder-list
  %h3.title.first Neue Initiativen
  %ul
    - @initiatives.recent.each do |initiative|
      %li
        %span
          - if initiative.user
            - if current_user
              = link_to initiative.user.username, profile_path(initiative.user)
            - else
              = link_to initiative.user.username, '#', "data-reveal-id" => "login-window"
            %br/
        = link_to initiative_path(initiative) do
          = truncate(initiative.title, :length => 80, :omission => '...')
  = link_to "Alle Initiativen", initiatives_path, :class => "alle"

app/views/widgets/_recent_neuigkeiten.html.haml
.holder-list
  %h3.title.second Veranstaltungen
  %ul
    - Neuigkeiten.recent.each do |neuigkeit|
      %li
        = link_to neuigkeiten_path(neuigkeit) do
          %span Aachen
          %br/
          = truncate(neuigkeit.title, :length => 50, :omission => '...')
    = link_to "Alle Veranstaltungen", neuigkeitens_path, :class => "alle"

app/views/widgets/_recent_updated_initiatives.html.haml
#widget.shape.grey
  %h4
    %span.icon-wrench.icon.red
    Aktive Initiativen
  %ul.no-bullet
    - Initiative.active.each do |initiative|
      %li
        -#= link_to image_tag(avatar_url(initiative.user, 25), alt: initiative.user.username, width: "25", height: "25"), profile_path(initiative.user)
        - if initiative.user
          - if current_user
            = link_to initiative.user.username, profile_path(initiative.user)
          - else
            initiative.user.username
          |
        = truncate(initiative.title, :length => 80, :omission => '...')
        -#= truncate(initiative.content, :length => 60, :omission => '...').html_safe
        = link_to "mehr", initiative_path(initiative)
  = link_to "mehr Initiativen", initiatives_path

app/views/widgets/_recent_vorlagen.html.haml
.holder-list.fourth
  %h3.title.fourth Rats-Infos
  - if @antraeges.present?
    %ul
      - @antraeges.recent.each do |antraege|
        %li
          = link_to antraege_path(antraege) do
            %span
              = antraege.kommune
            %br/
            = truncate(antraege.title, :length => 80, :omission => '...')
  - else
    %ul
      %li
        Keine Rats-Infos
  = link_to "Alle Rats-Infos", antraeges_path, :class => "alle"

app/views/widgets/_start_initiative.html.haml
- if current_user
  = link_to new_initiative_path, :class => "start" do
    Jetzt eigene
    %br>/
    Initiative starten!
- else
  = link_to '#', "data-reveal-id" => "login-window", class: "start" do
    Jetzt eigene
    %br>/
    Initiative starten!

app/views/widgets/_static.html.haml
= widget.content.html_safe

app/views/widgets/edit.html.haml
- title "Widget bearbeiten"

.row
  .large-10.columns
    #content
      %h1
        Widget bearbeiten
      = render 'form'

app/views/widgets/index.html.haml
= title "Widgets"

.row
  .large-12.columns
    #content
      .row
        .large-6.columns
          %h1 Widgets
        .large-6.columns
          = link_to "Neues Widget", new_widget_path, :class => "button radius right"

      .row
        .large-4.columns
          Widget-Typ
        .large-4.columns
          Erscheint
        .large-4.columns
          Funktionen
      - @widgets.each do |widget|
        .row
          .large-4.columns
            %p
              = link_to widget.name, edit_widget_path(widget)
          .large-4.columns
            %p
              - widget.placements.each do |placement|
                = placement.controller
          .large-4.columns
            - if can? :edit, widget
              = link_to 'Bearbeiten', edit_widget_path(widget)
            - if can? :destroy, widget
              = link_to 'Löschen', widget, :method => :delete, :data => { :confirm => 'Sind Sie sich sicher?' }

app/views/widgets/new.html.haml
- title "Neues Widget"

.row
  .large-10.columns
    #content
      %h1
        Neues Widget
      = render 'form'